### ISSUE TITLE
5GB size limit

### ISSUE THREAD

**Issue by mmadraimov92** [MartijnHols/actions-cache#4]
Hello, first of all thank you for the alternative actions-cache. I use it to control when to restore and save cache.

Recently I started hitting 5GB limit when uploading cache. However Github has increased cache size limit to 10GB. https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

**Comment by MartijnHols** [comment]
Hey, glad to hear you find this useful. I don't know when I'll have time to merge the changes from upstream into this repository. If you require this change soon, please consider opening a PR. I reckon it was this commit that increased the limit: https://github.com/MartijnHols/actions-cache/commit/eb0698d1c508f8573fddfe25566f10a4b1344504

**Comment by MartijnHols** [comment]
I just merged all changes up to 3.0.11 of actions/cache into the repository, so this should now be included.
